<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ShopOrderModel extends Model
{

    protected $table = 'g5_shop_order';
    protected $primaryKey = 'od_idx';
    public $timestamps = false;

    protected $fillable = [
        'od_id',
        'od_id_org',
        'od_date',
        'od_group_code',
        'od_group_code_org',
        'mb_code',
        'mb_id',
        'mb_branch_code',
        'mb_branch_gubun_type',
        'level_ca_id',
        'level_ca_id2',
        'level_ca_id2_name',
        'level_ca_id3',
        'level_ca_id4',
        'level_ca_id5',
        'chain_ca_id',
        'chain_ca_id2',
        'chain_ca_id3',
        'chain_ca_id4',
        'chain_ca_id5',
        'mb_level',
        'mb_sendcost',
        'mb_order_amount_select',
        'mb_order_amount',
        'mb_sendcost_amount_select',
        'mb_sendcost_amount',
        'mb_cs_delivery',
        'mb_cs_mon',
        'mb_cs_tue',
        'mb_cs_wed',
        'mb_cs_thu',
        'mb_cs_fri',
        'mb_cs_sat',
        'mb_cs_sun',
        'od_gubun',
        'od_gubun_type',
        'od_delivery_step',
        'od_delivery_step_chk',
        'od_delivery_day',
        'od_delivery_date',
        'mb_od_delivery_day',
        'mb_od_delivery_date',
        'delivery_car_code',
        'delivery_mb_code',
        'delivery_mb_name',
        'mb_delivery_car_code',
        'mb_delivery_mb_code',
        'mb_delivery_mb_name',
        'delivery_order1',
        'delivery_order2',
        'delivery_order3',
        'mb_sales_staff_code',
        'mb_sales_staff_name',
        'mb_manager_staff_code',
        'mb_manager_staff_name',
        'is_admin_data',
        'od_pwd',
        'od_company',
        'od_name',
        'od_email',
        'od_tel',
        'od_hp',
        'od_zip1',
        'od_zip2',
        'od_addr1',
        'od_addr2',
        'od_addr3',
        'od_addr_jibeon',
        'od_b_company',
        'od_b_name',
        'od_b_tel',
        'od_b_hp',
        'od_b_zip1',
        'od_b_zip2',
        'od_b_addr1',
        'od_b_addr2',
        'od_b_addr3',
        'od_b_addr_jibeon',
        'od_b_addr_sido',
        'od_b_addr_gugun',
        'od_deposit_name',
        'od_memo',
        'od_cart_count',
        'od_cart_price',
        'od_cart_price_change',
        'od_cart_coupon',
        'od_send_cost',
        'od_send_cost2',
        'od_send_coupon',
        'od_coupon',
        'od_receipt_price',
        'od_credit_receipt_price',
        'od_temp_point',
        'od_temp_point_reserve',
        'od_receipt_point',
        'od_bank_account',
        'bank_account',
        'od_receipt_time',
        'od_misu',
        'od_pg',
        'od_tno',
        'od_app_no',
        'od_escrow',
        'od_tax_flag',
        'od_tax_mny',
        'od_vat_mny',
        'od_free_mny',
        'od_status',
        'od_shop_memo',
        'od_hope_date',
        'od_tax_type',
        'od_tax_use',
        'od_protect_service',
        'od_cash_hp',
        'od_cash_company_no',
        'od_tax_company_no',
        'od_tax_company',
        'od_tax_name',
        'od_tax_zip',
        'od_tax_addr1',
        'od_tax_addr2',
        'od_tax_addr3',
        'od_tax_addr_jibeon',
        'od_tax_job',
        'od_tax_product',
        'od_time',
        'od_mobile',
        'od_ip',
        'od_credit_case',
        'od_settle_case',
        'od_is_charge',
        'pt_prev_charge',
        'pt_prev_reserve',
        'pt_prev_balance',
        'pt_sales',
        'pt_delivery',
        'pt_sales_delivery',
        'pt_charge',
        'pt_reserve',
        'pt_subtotal',
        'pt_cur_charge',
        'pt_cur_reserve',
        'pt_cur_balance',
        'od_test',
    ];

    public static function GetShopOrder()
    {

    }

}